'use client';
import {useState} from 'react';
import type {Project} from '@/lib/nepsa';
import {evaluate,rank,criteria,scoresFor,validateImport} from '@/lib/nepsa';
import {compareScenario,contributions,detailedCsv,historyChanges,parseHistory,parseScenarios,persistHistory,serializeScenarios,regionBounds,serializeHistory,snapshot} from '@/lib/analysis';
import type {Snapshot} from '@/lib/analysis';
import {MAX_BACKUP_BYTES,MODEL_VERSION,workspaceError} from '@/lib/workspace';
import {Button} from '@/components/ui/button';
import {Editor,Matrix} from './evaluation';

const fmt=(n:number|null|undefined)=>n==null?'—':n.toFixed(2);
function download(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const fingerprint=(p:Project|undefined)=>{if(!p)return '';try{return JSON.stringify(validateImport({version:1,projects:[p]}).projects[0]);}catch{return '';}};
const HISTORY='nepsa-evaluation-history-v1';
// throw된 Error를 그대로 문자열로 만들면 'Error:' 접두사가 화면에 노출된다.
const say=(e:unknown)=>e instanceof Error?e.message:'작업을 완료하지 못했습니다.';
const MAX_HISTORY=20;

export function Explanation({project}:{project:Project}){
 const result=evaluate(project),bounds=regionBounds(project),items=contributions(project);
 return <section className="panel insight"><h2>평가 결과 해석</h2><p>{result.eligible?`${result.region} 영역 · 기대성과 ${fmt(result.ret)}점 / 위험 ${fmt(result.risk)}점`:result.grade==='영역 밖'?'원천기술형은 기대성과 60점 이상, 위험 40점 이상일 때만 영역을 부여합니다. 위험 40점 미만은 낮은 등급을 뜻하지 않습니다.':'미입력 또는 잘못된 입력이 있어 종합 판정을 완료할 수 없습니다.'}</p>
 {bounds&&<p>현재 영역 범위: 기대성과 {bounds.returnMin} 이상~{bounds.returnMax}{bounds.returnMax===100?' 이하':' 미만'}, 위험 {bounds.riskMin} 이상~{bounds.riskMax}{bounds.riskMax===100?' 이하':' 미만'}. {bounds.returnMax<100&&`다음 성과 구간까지 ${(bounds.returnMax-result.ret!).toFixed(2)}점입니다.`} 경계를 넘더라도 같은 영역이 유지될 수 있습니다.</p>}
 {project.mode==='direct'?<p className="caption">종합점수 직접 입력 과제는 지표별 기여와 강약점을 분석할 원점수가 없습니다.</p>:<div className="insight-columns">{(['return','risk']as const).map(axis=><div key={axis}><h3>{axis==='return'?'성과를 구성하는 항목':'위험을 구성하는 항목'}</h3>{items.filter(c=>c.axis===axis).sort((a,b)=>(b.points??-1)-(a.points??-1)).map(c=><div className="contribution-row" key={c.id}><span>{c.name} <small>{c.score??'—'} / 5</small></span><meter min={0} max={25} value={c.points??0} aria-label={`${c.name} 축 기여 ${fmt(c.points)}점`}/><strong>{fmt(c.points)}점</strong></div>)}</div>)}</div>}
 <p className="caption">기여점수는 (지표점수−1)÷4×가중치입니다. 높은 기여가 인과관계나 개선 가능성을 입증하지는 않습니다. 환산식과 IP 반올림은 구현 가정입니다.</p></section>;
}

export default function AnalysisPanel({projects,active}:{projects:Project[];active:Project|undefined}){
 const [draft,setDraft]=useState<Project|null>(null),[baseline,setBaseline]=useState(''),[scenarioName,setScenarioName]=useState('기준'),[scenarios,setScenarios]=useState<{name:string;project:Project}[]>([]);
 const [selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState('');
 const [history,setHistory]=useState<Snapshot[]>([]),[loaded,setLoaded]=useState(false),[expected,setExpected]=useState<string|null>(null),[historyId,setHistoryId]=useState(''),[label,setLabel]=useState('');
 const draftError=draft?workspaceError([draft]):'',stale=draft&&baseline!==fingerprint(projects.find(p=>p.id===draft.id));
 const changes=draft&&!draftError&&!stale?compareScenario(projects,draft):[];
 const validSelected=selected.filter(id=>projects.some(p=>p.id===id));
 const chosen=projects.filter(p=>validSelected.includes(p.id)),old=history.find(s=>s.id===historyId);
 function load(){try{const value=localStorage.getItem(HISTORY);const next=value?parseHistory(value):[];setHistory(next);setExpected(value);setLoaded(true);setHistoryId(next[0]?.id||'');setMessage('평가 이력을 불러왔습니다.');}catch(e){setMessage(say(e));}}
 function saveHistory(next:Snapshot[]){const text=persistHistory(localStorage,HISTORY,next,expected);setExpected(text);setHistory(next);}
 function record(){try{if(history.length>=MAX_HISTORY)throw new Error(`평가 이력은 최대 ${MAX_HISTORY}회까지 보관합니다. 오래된 이력을 삭제한 뒤 저장하세요.`);const s=snapshot(projects,label,crypto.randomUUID(),new Date().toISOString());saveHistory([s,...history]);setHistoryId(s.id);setLabel('');setMessage('현재 전체 포트폴리오를 이력에 저장했습니다.');}catch(e){setMessage(say(e));}}
 function start(){if(!active)return;if(draft&&!window.confirm('현재 시나리오 작업을 지우고 새 분석을 시작할까요? 필요한 경우 먼저 시나리오 백업을 내려받으세요.'))return;setDraft(structuredClone(active));setBaseline(fingerprint(active));setScenarioName('기준');setScenarios([]);}
 function remember(){if(!draft||draftError||stale)return;const name=scenarioName.trim();if(!name){setMessage('시나리오 이름을 입력하세요.');return;}if(scenarios.length>=3&&!scenarios.some(s=>s.name===name)){setMessage('최대 3개까지 보관할 수 있습니다. 기존 시나리오 이름으로 보관하면 해당 시나리오가 갱신됩니다.');return;}setScenarios(prev=>[...prev.filter(s=>s.name!==name),{name,project:structuredClone(draft)}]);setMessage('시나리오를 보관했습니다. 새로고침하기 전에 시나리오 백업을 내려받으세요.');}
 return <div className="advanced-analysis">
 {message&&<output className="notice">{message}</output>}
 {active&&<Explanation project={active}/>}
 <section className="panel insight"><h2>시나리오 분석</h2><p>포트폴리오에서 선택한 과제의 복사본을 편집합니다. 실제 평가에는 반영되지 않습니다. 낙관·기준·비관 등 최대 3개를 보관해 비교할 수 있습니다.</p><Button onClick={start} disabled={!active||!!workspaceError(active?[active]:[])}>선택 과제로 새 분석 시작</Button><label className="scenario-import">시나리오 백업 불러오기<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>MAX_BACKUP_BYTES)throw new Error('5MB 이하 파일을 선택하세요.');const s=parseScenarios(await f.text());if(!window.confirm('현재 시나리오 작업을 백업으로 교체할까요? 원본 포트폴리오는 유지됩니다.'))return;setDraft(s.draft);setBaseline(JSON.stringify(s.base));setScenarioName(s.name);setScenarios(s.scenarios);setMessage(s.model===MODEL_VERSION?'시나리오를 복원했습니다. 기준 과제가 현재 원본과 다르면 순위 비교를 중지합니다.':'현재 모델로 다시 계산합니다. 백업 당시 모델과 달라 결과가 달라질 수 있습니다.');}catch(err){setMessage(say(err));}}}/></label>
 {draft&&<><h3>{draft.name}</h3>{stale&&<p role="alert" className="notice warning">원본 과제가 변경되었거나 삭제되었습니다. 새 분석을 시작해 기준을 갱신하세요.</p>}{draftError&&<p role="alert">{draftError}</p>}<div className="analysis-actions"><label>시나리오 이름<input value={scenarioName} maxLength={100} onChange={e=>setScenarioName(e.target.value)}/></label><Button onClick={remember} disabled={!!draftError||!!stale}>현재 시나리오 보관</Button><Button variant="outline" disabled={!!draftError||!scenarioName.trim()} onClick={()=>{try{download('NEPSA-시나리오.json',serializeScenarios({version:1,kind:'nepsa-scenarios',model:MODEL_VERSION,base:JSON.parse(baseline) as Project,draft,name:scenarioName,scenarios}));}catch(e){setMessage(say(e));}}}>시나리오 JSON 백업</Button></div>
 <div className="comparison-scroll"><table><caption>보관한 시나리오 · 현 포트폴리오에 해당 과제만 대체한 순위</caption><thead><tr><th>시나리오</th><th>성과</th><th>위험</th><th>영역</th><th>순위</th><th>편집</th></tr></thead><tbody>{scenarios.map(s=>{const e=evaluate(s.project),r=!stale?compareScenario(projects,s.project).find(c=>c.after.id===s.project.id)?.after.rank:null;return <tr key={s.name}><th>{s.name}</th><td>{fmt(e.ret)}</td><td>{fmt(e.risk)}</td><td>{e.region}</td><td>{r??'—'}</td><td><Button variant="ghost" onClick={()=>{setDraft(structuredClone(s.project));setScenarioName(s.name);}}>불러오기</Button></td></tr>;})}</tbody></table></div>
 {changes.length>0&&<><div className="insight-columns"><Matrix rows={changes.map(c=>c.before)} type={draft.type} selected={draft.id} onSelect={()=>{}}/><Matrix rows={rank(changes.map(c=>c.after))} type={draft.type} selected={draft.id} onSelect={()=>{}}/></div><p className="caption">왼쪽: 원본 · 오른쪽: 현재 시나리오. 원천기술형 영역 밖 과제는 점으로 표시되지 않습니다.</p><div className="comparison-scroll"><table><caption>전체 순위 변화 · 같은 유형</caption><thead><tr><th>과제</th><th>성과 전 → 후</th><th>위험 전 → 후</th><th>영역 전 → 후</th><th>순위 전 → 후</th></tr></thead><tbody>{changes.map(c=><tr key={c.before.id}><th>{c.before.name}</th><td>{fmt(c.before.ret)} → {fmt(c.after.ret)}</td><td>{fmt(c.before.risk)} → {fmt(c.after.risk)}</td><td>{c.before.eligible?c.before.region:c.before.grade} → {c.after.eligible?c.after.region:c.after.grade}</td><td>{c.before.rank??'—'} → {c.after.rank??'—'}</td></tr>)}</tbody></table></div></>}
 <Editor project={draft} scenario onChange={p=>setDraft({...p,id:draft.id,type:draft.type})} onDelete={()=>setDraft(null)} onCopy={()=>{}}/></>}
 </section>
 <section className="panel insight"><h2>평가 이력</h2><p>평가 시점의 전체 과제와 근거를 최대 20회 보관합니다. 이력은 현재 작업의 JSON 백업과 별도이며, 아래 이력 백업으로 옮길 수 있습니다.</p><div className="analysis-actions"><Button variant="outline" onClick={load}>{loaded?'이력 새로 불러오기':'저장된 이력 불러오기'}</Button><label>평가 시점·변경 이유<input value={label} maxLength={200} onChange={e=>setLabel(e.target.value)} placeholder="예: 1차 검토 · 시장자료 갱신"/></label><Button disabled={!loaded||!label.trim()} onClick={record}>현재 평가 이력 저장</Button><Button variant="outline" disabled={!loaded} onClick={()=>{try{download('NEPSA-평가이력.json',serializeHistory(history));}catch(e){setMessage(say(e));}}}>이력 백업</Button><label>이력 백업 병합<input type="file" accept=".json,application/json" disabled={!loaded} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>MAX_BACKUP_BYTES)throw new Error('5MB 이하 파일을 선택하세요.');const incoming=parseHistory(await file.text());const merged=[...history,...incoming.filter(s=>!history.some(h=>h.id===s.id))];saveHistory(merged);setMessage('기존 이력을 유지하며 새 이력을 병합했습니다. 같은 고유번호는 기존 값을 유지합니다.');}catch(err){setMessage(say(err));}}}/></label></div>
 {loaded&&<label>비교 기준 이력<select value={historyId} onChange={e=>setHistoryId(e.target.value)}><option value="">이력 선택</option>{history.map(s=><option key={s.id} value={s.id}>{s.label} · {new Date(s.createdAt).toLocaleString('ko-KR')}</option>)}</select></label>}
 {old&&<><Button variant="outline" onClick={()=>{if(window.confirm('선택한 이력을 삭제할까요? 필요한 경우 먼저 이력 백업을 내려받으세요.'))try{saveHistory(history.filter(s=>s.id!==old.id));setHistoryId('');setMessage('선택한 이력을 삭제했습니다.');}catch(e){setMessage(say(e));}}}>선택 이력 삭제</Button><p>{old.label} · 저장 모델 {old.model}{old.model!==MODEL_VERSION?' · 현재 모델과 달라 현재 기준으로 재계산합니다.':''}</p><div className="comparison-scroll"><table><caption>이전 평가 → 현재 평가 · 유형별 독립 순위</caption><thead><tr><th>과제</th><th>상태</th><th>성과</th><th>위험</th><th>영역</th><th>순위</th><th>변경 내용</th></tr></thead><tbody>{historyChanges(old.projects,projects).map(({id,previous:x,current:y,changes:diff})=><tr key={id}><th>{y?.name||x?.name}</th><td>{!x?'추가':!y?'삭제':x.type!==y.type?'유형 변경':'유지'}</td><td>{fmt(x?.ret)} → {fmt(y?.ret)}</td><td>{fmt(x?.risk)} → {fmt(y?.risk)}</td><td>{x?(x.eligible?x.region:x.grade):'—'} → {y?(y.eligible?y.region:y.grade):'—'}</td><td>{x?.rank??'—'} → {y?.rank??'—'}</td><td>{diff.length?<details><summary>{diff.length}개 변경</summary>{diff.map((text,i)=><p key={i}>{text}</p>)}</details>:'변경 없음'}</td></tr>)}</tbody></table></div></>}
 </section>
 <section className="panel insight"><h2>과제 비교</h2><p>최대 4개를 선택해 지표와 근거를 나란히 확인합니다. 다른 유형의 종합점수는 동일한 영역 기준으로 비교할 수 없습니다.</p><div className="project-checks">{projects.map(p=><label key={p.id}><input type="checkbox" checked={selected.includes(p.id)} disabled={validSelected.length>=4&&!validSelected.includes(p.id)} onChange={e=>setSelected(prev=>e.target.checked?[...prev.filter(id=>projects.some(p=>p.id===id)),p.id]:prev.filter(id=>id!==p.id))}/>{p.name}</label>)}</div>
 {chosen.length>0&&<div className="comparison-scroll"><table><caption>선택 과제 상세 비교</caption><thead><tr><th>항목</th>{chosen.map(p=><th key={p.id}>{p.name}</th>)}</tr></thead><tbody><tr><th>유형 / 영역 / 성과 / 위험</th>{chosen.map(p=>{const e=evaluate(p);return <td key={p.id}>{p.type==='company'?'기업주관':'원천기술'} / {e.eligible?e.region:e.grade} / {fmt(e.ret)} / {fmt(e.risk)}</td>;})}</tr>{criteria.map(c=><tr key={c.id}><th>{c.name} · {c.weight}%</th>{chosen.map(p=><td key={p.id}><strong>{p.mode==='direct'?'직접 입력 · 지표 없음':`${scoresFor(p)[c.id]??'미입력'} / 5`}</strong><p>{p.notes[c.id]||'근거 미작성'}</p><small>{['source','year','assumption','confidence'].map(k=>p.notes[`${c.id}:${k}`]).filter(Boolean).join(' · ')}</small></td>)}</tr>)}</tbody></table></div>}
 </section>
 <section className="panel insight"><h2>보고서 출력</h2><p>상세 CSV에는 유형별 순위, 12개 지표, 가중치, 기여점수와 평가 근거를 담습니다. Excel에서 열 수 있습니다. PDF는 포트폴리오 탭에서 선택한 과제와 전체 순위표를 인쇄하세요.</p><Button onClick={()=>download('NEPSA-상세평가.csv',detailedCsv(projects),'text/csv;charset=utf-8')} disabled={!!workspaceError(projects)}>Excel용 상세 CSV 내려받기</Button></section>
 </div>;
}
